// Unit tests for skill generator (GEN-01).
// Covers: skill artifact generation from long_prompt SKILL recommendations,
// null returns for non-applicable recs, YAML frontmatter correctness,
// schema validation of output, and special character escaping.

import { describe, it, expect } from 'vitest';
import { generateSkill } from '../../../src/generators/skill-generator.js';
import { generatedArtifactSchema } from '../../../src/generators/schemas.js';
import type { Recommendation } from '../../../src/schemas/recommendation.js';

function makeRecommendation(
  overrides: Partial<Recommendation> = {},
): Recommendation {
  return {
    id: 'rec-long-0',
    target: 'SKILL',
    confidence: 'HIGH',
    pattern_type: 'long_prompt',
    title: 'Long repeated prompt (250 words, 5x)',
    description:
      'A 250-word prompt has been used 5 times. Consider converting it to a reusable skill.',
    evidence: {
      count: 5,
      examples: [
        'Please analyze the codebase and identify all TypeScript files that import from the legacy module...',
      ],
    },
    suggested_action:
      'Create a skill in .claude/skills/ that encapsulates this prompt as a reusable workflow.',
    ...overrides,
  };
}

describe('generateSkill', () => {
  it('returns GeneratedArtifact with type skill for SKILL/long_prompt rec', () => {
    const result = generateSkill(makeRecommendation());
    expect(result).not.toBeNull();
    expect(result!.type).toBe('skill');
  });

  it('generates filename matching .claude/commands/<slug>.md pattern', () => {
    const result = generateSkill(makeRecommendation());
    expect(result).not.toBeNull();
    expect(result!.filename).toMatch(/^\.claude\/commands\/[\w-]+\.md$/);
  });

  it('generates content starting with YAML frontmatter', () => {
    const result = generateSkill(makeRecommendation());
    expect(result).not.toBeNull();
    const lines = result!.content.split('\n');
    expect(lines[0]).toBe('---');
    expect(result!.content).toContain('name:');
    expect(result!.content).toContain('description:');
    // Closing frontmatter delimiter
    const secondDash = lines.indexOf('---', 1);
    expect(secondDash).toBeGreaterThan(0);
  });

  it('includes prompt text from evidence.examples[0] in content', () => {
    const result = generateSkill(makeRecommendation());
    expect(result).not.toBeNull();
    expect(result!.content).toContain(
      'Please analyze the codebase and identify all TypeScript files that import from the legacy module...',
    );
  });

  it('ends content with auto-generated footer', () => {
    const result = generateSkill(makeRecommendation());
    expect(result).not.toBeNull();
    expect(result!.content).toContain(
      '*Auto-generated by harness-evolve (rec-long-0)*',
    );
  });

  it('returns null when rec.target is not SKILL', () => {
    const result = generateSkill(makeRecommendation({ target: 'HOOK' }));
    expect(result).toBeNull();
  });

  it('returns null when rec.pattern_type is not long_prompt', () => {
    const result = generateSkill(
      makeRecommendation({ pattern_type: 'repeated_prompt' }),
    );
    expect(result).toBeNull();
  });

  it('produces output that passes generatedArtifactSchema validation', () => {
    const result = generateSkill(makeRecommendation());
    expect(result).not.toBeNull();
    expect(() => generatedArtifactSchema.parse(result)).not.toThrow();
  });

  it('derives filename slug from recommendation title', () => {
    const result = generateSkill(makeRecommendation());
    expect(result).not.toBeNull();
    // Title: "Long repeated prompt (250 words, 5x)"
    // Expected slug: "long-repeated-prompt-250-words-5x"
    expect(result!.filename).toContain('long-repeated-prompt');
  });

  it('sets source_recommendation_id to the input rec.id', () => {
    const result = generateSkill(
      makeRecommendation({ id: 'rec-long-42' }),
    );
    expect(result).not.toBeNull();
    expect(result!.source_recommendation_id).toBe('rec-long-42');
  });

  it('sets metadata.pattern_type to long_prompt', () => {
    const result = generateSkill(makeRecommendation());
    expect(result).not.toBeNull();
    expect(result!.metadata.pattern_type).toBe('long_prompt');
  });

  it('escapes special characters in YAML frontmatter', () => {
    const result = generateSkill(
      makeRecommendation({
        title: 'Prompt with: colons and "quotes"',
        description:
          'Description with: special chars. Second sentence here.',
      }),
    );
    expect(result).not.toBeNull();
    // The frontmatter should safely handle colons/quotes
    const frontmatter = result!.content.split('---')[1];
    expect(frontmatter).toBeDefined();
    // Should contain escaped description (wrapped in quotes)
    expect(frontmatter).toContain('description:');
  });
});
