// Skill generator: converts long_prompt SKILL recommendations into
// .claude/commands/<name>.md file drafts. Pure function -- no filesystem
// access, no side effects. Returns null for non-applicable recommendations.

import type { Recommendation } from '../schemas/recommendation.js';
import type { GeneratedArtifact } from './schemas.js';
import { toSlug, escapeYaml, GENERATOR_VERSION, nowISO } from './schemas.js';

/**
 * Generate a skill file draft from a long_prompt SKILL recommendation.
 *
 * @param rec - A Recommendation object (typically from the long-prompts classifier)
 * @returns GeneratedArtifact with type 'skill', or null if the recommendation
 *          is not applicable (wrong target or pattern_type)
 */
export function generateSkill(rec: Recommendation): GeneratedArtifact | null {
  if (rec.target !== 'SKILL') return null;
  if (rec.pattern_type !== 'long_prompt') return null;

  const promptPreview = rec.evidence.examples[0] ?? '';
  const slugName = toSlug(rec.title);
  const firstSentence = rec.description.split('.')[0];

  const content = [
    '---',
    `name: ${escapeYaml(slugName)}`,
    `description: ${escapeYaml(firstSentence)}`,
    '---',
    '',
    `# ${rec.title}`,
    '',
    '## Instructions',
    '',
    promptPreview,
    '',
    '---',
    `*Auto-generated by harness-evolve (${rec.id})*`,
  ].join('\n');

  return {
    type: 'skill',
    filename: `.claude/commands/${slugName}.md`,
    content,
    source_recommendation_id: rec.id,
    metadata: {
      generated_at: nowISO(),
      generator_version: GENERATOR_VERSION,
      pattern_type: rec.pattern_type,
    },
  };
}
