// Slash command template generator for /evolve:apply

// Template version -- bump when content changes materially
const APPLY_TEMPLATE_VERSION = '4';

/**
 * Return the current apply template version for version-aware updates.
 */
export function getApplyTemplateVersion(): string {
  return APPLY_TEMPLATE_VERSION;
}

/**
 * Generate the Markdown content for the /evolve:apply slash command.
 *
 * This produces a comprehensive, self-contained workflow document that fully
 * specifies Claude's behavior when the command is invoked. The .md body IS
 * the context injected by Claude Code -- no CLAUDE.md preloading needed.
 */
export function generateApplyCommand(): string {
  return `---
name: apply
description: Review and apply pending harness-evolve recommendations one by one
disable-model-invocation: true
argument-hint: "[filter: all|high|medium|low]"
allowed-tools: Bash(npx harness-evolve *)
---
<!-- template-version: ${APPLY_TEMPLATE_VERSION} -->

# Evolve Apply

Review pending harness-evolve recommendations interactively. Apply, skip, or dismiss each one.

## Context

This command reads pending recommendations generated by \`/evolve:scan\` (model-driven analysis) or background analysis hooks. Findings are produced by the model analyzing your configuration and stored via the \`store-findings\` pipeline. It presents each recommendation for your decision. You can filter by confidence level using arguments.

Pending recommendations include both **problems** (must fix) and **suggestions** (optional improvements), each with a confidence level (HIGH/MEDIUM/LOW).

## Arguments

If \`$ARGUMENTS\` is provided:
- **"high"**, **"medium"**, or **"low"**: Filter to only show recommendations at that confidence level
- **"all"** or empty: Show all pending recommendations
- Unrecognized value: Show all pending recommendations and note that the filter was ignored

## Prerequisites

Before running, verify harness-evolve is available:

\`\`\`bash
npx harness-evolve --version
\`\`\`

- If the command prints a version number, proceed to Instructions.
- If the command fails with "not found" or similar error, install first:
  \`\`\`bash
  npm install -g harness-evolve
  \`\`\`
  Or for first-time setup:
  \`\`\`bash
  npx harness-evolve init
  \`\`\`

## Instructions

### Step 1: Read Pending Recommendations

\`\`\`bash
npx harness-evolve pending
\`\`\`

### Step 2: Check for Empty Results

If the command outputs no pending recommendations (empty array or zero items), inform the user:

> No pending recommendations. Run \`/evolve:scan\` to analyze your configuration and generate new recommendations.

Stop here if there are no recommendations.

### Step 3: Present Each Recommendation

For each pending recommendation, present using the card format from the Output Format section below. Include:
- Severity badge (**PROBLEM** or **SUGGESTION**)
- Confidence level (HIGH / MEDIUM / LOW)
- Title
- Description
- Evidence (what data or pattern triggered this)
- Suggested action

### Step 4: Ask User to Choose

For each recommendation, present numbered options:

**Choose an action:**
1. **Apply** -- Execute this recommendation now
2. **Skip** -- Leave it pending for later
3. **Dismiss** -- Permanently remove this recommendation
4. **Let Claude decide** -- Apply if HIGH confidence, skip if MEDIUM/LOW

Wait for the user to respond with a number (1-4). If the user responds with text instead of a number, map it to the closest option.

When the user chooses:
- **1 (Apply):**
  \`\`\`bash
  npx harness-evolve apply-one <id>
  \`\`\`
  Report the result (success or failure) and show what changed.

- **2 (Skip):** Leave it pending for future review. No CLI command needed.

- **3 (Dismiss):**
  \`\`\`bash
  npx harness-evolve dismiss <id>
  \`\`\`
  Confirm the recommendation has been dismissed.

- **4 (Let Claude decide):** If the recommendation has HIGH confidence, apply it (same as option 1). If MEDIUM or LOW, skip it (same as option 2).

### Step 5: Process Next Recommendation

After handling one recommendation, move to the next. Repeat Steps 3-4 for each.

### Step 6: Show Summary

After all recommendations are processed, show a summary:

> Done: **X** applied, **Y** skipped, **Z** dismissed.

## Output Format

Present each recommendation as a card:

\`\`\`
**[SEVERITY] [CONFIDENCE]** Title of the recommendation
Description text explaining the issue or opportunity.
- **Evidence:** What triggered this recommendation
- **Suggested:** Action to take

**Choose an action (1-4):**
1. Apply  2. Skip  3. Dismiss  4. Let Claude decide
\`\`\`

Where:
- SEVERITY is \`PROBLEM\` or \`SUGGESTION\`
- CONFIDENCE is \`HIGH\`, \`MEDIUM\`, or \`LOW\`

**Summary at end:**

> Done: **X** applied, **Y** skipped, **Z** dismissed.

If all were skipped or dismissed, suggest:

> Run \`/evolve:scan\` for fresh analysis if you'd like new recommendations.

## Error Handling

### CLI Command Fails

If \`npx harness-evolve pending\` exits with a non-zero code or outputs an error:

1. Show the error message to the user
2. Suggest: "Try running \`harness-evolve status\` to check installation health"
3. If "not found" error, suggest: "Run \`harness-evolve init\` to set up"

### Apply Fails

If \`npx harness-evolve apply-one <id>\` returns an error:

1. Show the error to the user
2. Do NOT retry automatically
3. Ask: "Would you like to **skip** or **dismiss** this recommendation instead?"

### Dismiss Fails

If \`npx harness-evolve dismiss <id>\` returns an error:

1. Show the error to the user
2. Continue to the next recommendation (do not block the workflow)

## Edge Cases

- **Only 1 recommendation pending:** Still show the full card format. Skip the "next recommendation" transition and go directly to summary.
- **User asks to stop mid-way:** Summarize what was processed so far and note how many remain pending.
- **Recommendation references a file that no longer exists:** Show a warning but still allow the user to apply, skip, or dismiss.
- **Filter returns zero matches:** Inform: "No [level] recommendations pending. Run without a filter to see all, or \`/evolve:scan\` for fresh analysis."

## Notes

- Recommendations are generated by \`/evolve:scan\` (model-driven configuration analysis) or automatic background analysis hooks.
- Applied recommendations modify configuration files (settings.json, CLAUDE.md, .claude/rules/, etc.).
- Dismissed recommendations will not reappear until a new scan generates them.
- Skipped recommendations remain pending for the next \`/evolve:apply\` session.
- For overall system health, run \`harness-evolve status\`.
`;
}
