// Slash command template generator for /evolve:apply

/**
 * Generate the Markdown content for the /evolve:apply slash command.
 *
 * This command instructs Claude Code to read pending recommendations,
 * present them interactively, and let the user apply, skip, or ignore each one.
 */
export function generateApplyCommand(): string {
  return `---
name: apply
description: Review and apply pending harness-evolve recommendations one by one
disable-model-invocation: true
argument-hint: "[filter: all|high|medium|low]"
---

# Evolve Apply

Review pending harness-evolve recommendations interactively. For each recommendation, you can choose to apply it, skip it for later, or permanently dismiss it.

## Arguments

If \`$ARGUMENTS\` is provided (e.g., "high", "medium", or "low"), filter recommendations to only show that confidence level. If empty or "all", show all pending recommendations.

## Instructions

### Step 1: Read Pending Recommendations

\`\`\`bash
npx harness-evolve pending
\`\`\`

If the command outputs no pending recommendations, inform the user:
> No pending recommendations. Run \`/evolve:scan\` to analyze your configuration and generate new recommendations.

### Step 2: Present Each Recommendation

For each pending recommendation, present the following:

- **Confidence level** (HIGH / MEDIUM / LOW)
- **Title** -- what the recommendation is about
- **Description** -- detailed explanation of the issue
- **Evidence** -- what data or pattern triggered this recommendation
- **Suggested action** -- what change is proposed

### Step 3: Ask User to Choose

For each recommendation, ask the user to choose one of three actions:

1. **Apply** -- Execute the recommendation. Run:
   \`\`\`bash
   npx harness-evolve apply-one <id>
   \`\`\`
   Report the result (success or failure) and show what changed.

2. **Skip** -- Do nothing for now. The recommendation stays pending for future review. No command needed.

3. **Ignore** -- Permanently dismiss this recommendation. Run:
   \`\`\`bash
   npx harness-evolve dismiss <id>
   \`\`\`
   Confirm the recommendation has been dismissed.

### Step 4: Continue or Finish

After processing each recommendation, move to the next one. When all recommendations have been processed, summarize what was done:
- How many applied
- How many skipped
- How many ignored

## Notes

- Recommendations are generated by \`harness-evolve scan\` or automatic background analysis
- Applied recommendations modify configuration files (settings.json, CLAUDE.md, .claude/rules/, etc.)
- Ignored recommendations will not appear in future \`/evolve:apply\` sessions
- Skipped recommendations remain pending and will reappear next time
`;
}
