// ClaudeMdApplier: handles auto-apply for HIGH-confidence CLAUDE_MD recommendations.
// Appends new sections to CLAUDE.md for generic pattern types. Refuses to
// auto-apply destructive patterns (scan_stale_reference, scan_redundancy) that
// require manual review. Uses write-file-atomic for safe writes.
// Creates backup of original CLAUDE.md before modification.

import { readFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import writeFileAtomic from 'write-file-atomic';
import type { Applier, ApplierOptions } from './index.js';
import type { Recommendation } from '../../schemas/recommendation.js';
import type { AutoApplyResult } from '../auto-apply.js';
import { paths } from '../../storage/dirs.js';

/** Pattern types that require manual review — no destructive auto-apply. */
const DESTRUCTIVE_PATTERNS = new Set([
  'scan_stale_reference',
  'scan_redundancy',
]);

export class ClaudeMdApplier implements Applier {
  readonly target = 'CLAUDE_MD';

  canApply(rec: Recommendation): boolean {
    return rec.confidence === 'HIGH' && rec.target === 'CLAUDE_MD';
  }

  async apply(
    rec: Recommendation,
    options?: ApplierOptions,
  ): Promise<AutoApplyResult> {
    try {
      // Pattern-type guard: refuse destructive patterns
      if (DESTRUCTIVE_PATTERNS.has(rec.pattern_type)) {
        return {
          recommendation_id: rec.id,
          success: false,
          details: `Pattern type '${rec.pattern_type}' requires manual review — cannot safely auto-apply`,
        };
      }

      // Resolve CLAUDE.md path
      const claudeMdPath =
        options?.claudeMdPath ??
        join(process.cwd(), 'CLAUDE.md');

      // Read existing content (empty string if file doesn't exist)
      let existingContent = '';
      try {
        existingContent = await readFile(claudeMdPath, 'utf-8');
      } catch {
        // File does not exist — will be created
      }

      // Create backup if content exists
      if (existingContent) {
        const backupDir = join(paths.analysis, 'backups');
        await mkdir(backupDir, { recursive: true });
        const backupFile = join(backupDir, `claudemd-backup-${rec.id}.md`);
        await writeFileAtomic(backupFile, existingContent);
      }

      // Build new section to append
      const newSection = [
        '',
        '',
        `## ${rec.title}`,
        '',
        rec.suggested_action,
        '',
        '---',
        `*Auto-generated by harness-evolve (${rec.id})*`,
        '',
      ].join('\n');

      // Append section to existing content
      const updatedContent = existingContent + newSection;

      // Ensure parent directory exists
      await mkdir(dirname(claudeMdPath), { recursive: true });

      // Write updated content atomically
      await writeFileAtomic(claudeMdPath, updatedContent);

      return {
        recommendation_id: rec.id,
        success: true,
        details: `Appended section: ${rec.title}`,
      };
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      return {
        recommendation_id: rec.id,
        success: false,
        details: message,
      };
    }
  }
}
