// RuleApplier: handles auto-apply for HIGH-confidence RULE recommendations.
// Creates .claude/rules/evolve-{pattern_type}.md files with the recommendation
// title, description, and suggested action. Create-only: never overwrites
// existing rule files to respect user customizations (Pitfall 18).

import { writeFile, access, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import type { Applier, ApplierOptions } from './index.js';
import type { Recommendation } from '../../schemas/recommendation.js';
import type { AutoApplyResult } from '../auto-apply.js';

export class RuleApplier implements Applier {
  readonly target = 'RULE';

  canApply(rec: Recommendation): boolean {
    return rec.confidence === 'HIGH' && rec.target === 'RULE';
  }

  async apply(
    rec: Recommendation,
    options?: ApplierOptions,
  ): Promise<AutoApplyResult> {
    const rulesDir =
      options?.rulesDir ??
      join(process.env.HOME ?? '', '.claude', 'rules');
    const fileName = `evolve-${rec.pattern_type}.md`;
    const filePath = join(rulesDir, fileName);

    // Create-only guard: never overwrite existing files (Pitfall 18)
    try {
      await access(filePath);
      return {
        recommendation_id: rec.id,
        success: false,
        details: `Rule file already exists: ${fileName}`,
      };
    } catch {
      // File does not exist — proceed to create
    }

    try {
      await mkdir(rulesDir, { recursive: true });

      const content = [
        `# ${rec.title}`,
        '',
        rec.description,
        '',
        '## Action',
        '',
        rec.suggested_action,
        '',
        '---',
        `*Auto-generated by harness-evolve (${rec.id})*`,
      ].join('\n');

      await writeFile(filePath, content, 'utf-8');

      return {
        recommendation_id: rec.id,
        success: true,
        details: `Created rule file: ${fileName}`,
      };
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      return {
        recommendation_id: rec.id,
        success: false,
        details: message,
      };
    }
  }
}
